import { IntakeStep } from './types';

export const intakeStepsKr: IntakeStep[] = [
  {
    id: 1,
    fieldName: 'childAge',
    question: '자녀의 나이는 어떻게 되나요?',
    type: 'single-select',
    options: [
      '만 2세 미만',
      '만 2-3세',
      '만 4-5세',
      '초등 저학년',
      '초등 고학년',
      '중학생 이상',
    ],
  },
  {
    id: 2,
    fieldName: 'diagnosedBy',
    question: '진단 또는 평가는 어디까지 진행되었나요?',
    type: 'single-select',
    options: [
      '소아발달클리닉 또는 소아정신과에서 진단받았어요',
      '심리검사센터 또는 발달클리닉에서 평가받았어요',
      '어린이집/유치원/학교에서 평가를 권유받았어요',
      '아직 공식 진단은 없어요',
    ],
  },
  {
    id: 3,
    fieldName: 'diagnoses',
    question: '현재 들은 진단명이나 어려움은 무엇인가요?',
    subtitle: '정확한 용어를 몰라도 괜찮습니다. 해당되는 것을 모두 선택하세요.',
    type: 'multi-select',
    options: [
      '자폐스펙트럼장애',
      'ADHD',
      '언어발달지연',
      '감각처리 어려움',
      '지적장애 또는 전반적 발달지연',
      '정확한 용어는 아직 모르겠어요',
    ],
  },
  {
    id: 4,
    fieldName: 'currentSupport',
    question: '현재 받고 있는 치료나 지원이 있나요?',
    type: 'multi-select',
    options: [
      '아직 아무 지원도 없어요',
      '발달센터',
      '언어치료',
      '작업치료',
      '행동발달치료 또는 ABA',
      '발달재활서비스 바우처',
      '특수교육 또는 개별화교육계획',
    ],
  },
  {
    id: 5,
    fieldName: 'topConcerns',
    question: '지금 가장 걱정되는 것은 무엇인가요?',
    subtitle: '최대 3개까지 선택하세요.',
    type: 'multi-select',
    maxSelections: 3,
    options: [
      '무엇부터 해야 할지 모르겠어요',
      '병원 예약이 너무 어려워요',
      '치료사를 찾고 싶어요',
      '말과 의사소통이 걱정돼요',
      '집에서의 행동이 힘들어요',
      '어린이집/유치원/학교가 걱정돼요',
      '복지 서비스와 바우처가 궁금해요',
      '부모인 제가 너무 지쳤어요',
    ],
  },
  {
    id: 6,
    fieldName: 'freeText',
    question: '자녀나 현재 상황에 대해 더 적고 싶은 내용이 있나요?',
    subtitle: '선택 사항입니다. 짧게 적어도 괜찮습니다.',
    type: 'textarea',
    optional: true,
    placeholder: '예: 최근 어린이집에서 평가를 권유받았고, 병원 예약은 아직 못 잡았습니다.',
  },
];
